### ISSUE TITLE
error in npm installation

### ISSUE THREAD

**Issue by YutoKa** [kazuyaseki/figma-code-transformer#19]
\figma-code-transformer>npm run build

> figma-code-transformer@0.0.1 build
> build-figma-plugin --typecheck --minify

info Type checking...
error TypeScript error

    src/hooks/useFigmaLayerData.ts:78:71 - error TS2345: Argument of type 'never[]' is not assignable to parameter of type 'string'.

    78           .map((summaryPrompt) => createChatCompletion(summaryPrompt, [], true))
                                                                             ~~

**Comment by kazuyaseki** [comment]
@YutoKa 
Thanks for filing the issue! I fixed the typings and should be able to build now

**Comment by YutoKa** [comment]
Thanks for fixing the issue! I will try it later.
